spring:
  application:
    name: claim
  datasource:
    url: jdbc:h2:mem:testdb
    username: dbuser
    password: dbpass
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
server:
  port: 8080
  servlet:
    context-path: /api/v1
    tomcat:
      max-threads: 100
      max-connections: 1000
      accept-count: 100
      max-http-post-size: 100MB

# Needs a Spring Cloud Config Server to dynamically load properties
rate:
  limit:
    capacity: 5
    tokens: 5
    minutes: 1

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info